site_name: microfading

theme:
  name: "material"
  
nav:
  - index.md
  - installation.md  
  - Documentation: 
       - Tutorials:
           - first-steps.md
           - assess-light-sensitivity.md
           - generate-report.md
       - How-to-guides:     
           - manage-databases.md       
           - retrieve-test-datasets.md
           - create-MFT-class-instance.md
           - visualize-data.md
       - explanation.md
       - references.md 
  
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']  # Make sure mkdocstrings looks in the 'src' directory
          
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
