site_name: microfading

theme:
  name: "material"
  logo: images/MF_logo_wbg-circle.png
  features:
    - content.code.copy
 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/g-patin/microfading
      name: GitHub

  
nav:
  - index.md
  - installation.md  
  - microfading.md
  - Tutorials:
      - get-started.md
      - configuration-info.md
      - databases-management.md
      - assess-light-sensitivity.md
      - generate-report.md
      - rawdata-processing.md
      - data-visualization.md      
  - How-to-guides:             
      - retrieve-test-datasets.md
      - create-databases.md
      - Create an MFT class instance: create-MFT-class-instance.md      
  - Explanation:
      - package-usage.md
      - datafiles.md
      - config-vs-database.md
      - language-setting.md
  - References: references.md 
  
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']  # Make sure mkdocstrings looks in the 'src' directory
          
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
      
extra_css:
  - css/custom.css
  
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
