site_name: microfading

theme:
  name: "material"
  
nav:
  - index.md
  - installation.md  
  - Documentation: 
       - tutorials.md
       - How-to-guides: 
           - how-to-guides.md
           - retrieve-test-datasets.md
       - reference.md
       - installation.md
  
  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']  # Make sure mkdocstrings looks in the 'src' directory
          
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
